### ISSUE TITLE
Component boolean attributes are empty strings.

### ISSUE THREAD

**Issue by jleeson** [OutwalkStudios/jolt#11]
Currently when a component attribute is parsed it assigns the value to its name. if there is no value we expect it to be true but it returns an empty string. This can result in unexpected behavior and so it should be changed to have the value of true.

To solve this, the `getComponentAttributes` in `Runtime.js` should be updated to check if the value of the attribute is an empty string, if it is, replace the value with `true`

**Comment by sandy9808** [comment]
I will correct the bug

**Comment by sandy9808** [comment]
This error shows up on typing npm start, why ?
$ npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-10-03T01_29_15_030Z-debug.log

**Comment by jleeson** [comment]
@sandy9808 that error occurs because there is no "start" script in package.json.

**Comment by sandy9808** [comment]
How will i debug then, if there is no "start" script in package.json ?

**Comment by jleeson** [comment]
Jolt does not implement a "start" script, it provides scripts only for building the codebase. There currently is not automated testing either which would be "npm test". So in order to debug, you can generate a new project using @jolt/cli, write your code, and then try using the new build output of jolt from the "npm run build" script inside the project.

You can go through the package.json file to see what scripts are available.
