### ISSUE TITLE
Allow returning null in Component render function.

### ISSUE THREAD

**Issue by jleeson** [OutwalkStudios/jolt#13]
When you want to conditionally render something, with one of the options being rendering nothing, you currently need to return a blank template. It would be nice to be able to use a simple `return` without throwing an error.

This would involve code changes in the `TemplateEngine`.

**Comment by sandy9808** [comment]
Hey there again, is this right ?
![image](https://user-images.githubusercontent.com/58395595/94981324-e99e8480-054e-11eb-8adc-d157ff4c7b09.png)

**Comment by jleeson** [comment]
@sandy9808 Hey, for this issue im looking to add support for returning null inside a components render method.

something like this:

```js
class MyComponent extends Component {

    render({ visible }) {
        if(!visible) return; // This is what should be supported

        return html``;
    }
}
```

In your screenshot, your using JSX which is not supported in Jolt. Jolt instead chooses to use native template literal strings for writing markup.

A component is rendered by either using the custom element tag or calling `Component.mount(MyComponent, document.body);`

**Comment by ashikvarma11** [comment]
@jleeson  I would like to try this. Can I?

**Comment by sandy9808** [comment]
No idea how to do this..

**Comment by jleeson** [comment]
@ashikvarma11 go for it!

**Comment by jleeson** [comment]
@sandy9808 you can take a look at the readme for the jolt package to get a better understanding of the api. For this issue in particular the change would need to happen in the TemplateEngine.js file to allow null/undefined values instead of a template.
